### DISCUSSION TITLE
ZWEGENER could not load the configuration

### DISCUSSION THREAD

**Discussion by mainframe-JMF** [zowe/docs-site#4240] [Q&A]
Hello,

I was trying to load the ZOWE configuration using JCL but it is ending up with the error message.

READY                                                                      
ISPSTART CMD(%ZWEGEN00 generate verbose )                                  
ISPF system data set allocation error - press Enter to continue.           
Log file allocation error - ISPF will operate without a log data set.      
Data set 'TECH.XXXXX.SPFLOG1.LIST' in use by another user, try later.    
execio * diskr myschema (finis stem !contentToRead.                        
execio * diskr myschema (finis stem !contentToRead.                        
execio * diskr myconfig (finis stem !contentToRead.                        
ConfigMgr is about to add a configuration.                                 
ConfigMgr added a configuration.                                           
ConfigMgr is about to set trace level to 1.                                
ConfigMgr set trace level to 1.                                            
ConfigMgr is about to load your schemas.                                   
ConfigMgr loaded your schemas.                                             
ConfigMgr is about to set the member name for parameter library.           
ConfigMgr set the parameter library member name.  
ConfigMgr is about to process your configuration.         
ConfigMgr has processed your configuration.               
ConfigMgr is about to load your configuration.            
ConfigMgr could not load your configuration.              
status = 2                                                
ISPD117                                                   
The initially invoked CLIST ended with a return code = 8  

======

CEE3608I The following messages pertain to the invocation command run-time optio
CEE3606I The string '        CELQPTBL' was too long and was ignored.JSON: write error, rc -1, return code 0, reason code 00000000
JSON: write error, rc -1, return code 0, reason code 00000000                   
JSON: write error, rc -1, return code 0, reason code 00000000        

==============

overload mgr=0x1C4D3668 config=01C4D44F0 pathElement=0x5008695214               
before read YAML mgr=0x1C4D3668 file=/u/xxxxx/zowe.yaml                       
yaml doc at 0x1B7DAC68, allowMissing=0 wasMissing=0                             
overlay = 0x50086956C4 tail=0x50086952A4 nullAllowed=0                          
before read YAML mgr=0x1C4D3668 file=/zowe/files/defaults.yaml                  
yaml doc at 0x1B7DACD8, allowMissing=0 wasMissing=0                             
Overload status = 0                                                             
returning evalblock at 0x1B537E30                                               
00000000  00000000 00000022 00000001 00000000  F2000000 00000000 00000000 000000        

Not sure what exactly is missing here due to which the configuration loading is failing. Is there a place to check where the configuration load trace can be found and see the place where it is failing ?

**Comment by Martin-Zeithaml** [comment]
Hello, 

could you share the `zowe.yaml` file?

It might be a problem with templating, but I am not able to reproduce it on our system.

Regards, Martin

**Comment by mainframe-JMF** [comment]
Hello,

I am attaching the ZOWE.YAML file.
[TEST.YAML.txt](https://github.com/user-attachments/files/19305355/TEST.YAML.txt)

**Comment by Martin-Zeithaml** [comment]
Hi, there are several problems:
* One of the problems is, that the `status=2` is not helpful and there is no additional output to guide you to fix the problem
  * This is problem of our internal parser
* There are problems in the configuration itself:
  * Line 33: `zowe:/zowe` should be `zowe:`
  * Line 429: spaces before the last "r": `certificateAuthorities: /zowe/keystore/local_ca/local_ca.ce       r`
  * Line 100+, if the certificate already exists, you can comment or remove entire `zowe.setup.certificate` section. Otherwise there are problems with incomplete properties and indentation, this is probably intended setup:
```yaml
zowe:
  setup:
    certificate:
      # Type of certificate storage. Valid values are: PKCS12, JCERACFKS. APIML additionally supports: JCEKS, JCECCAKS, JCECCARACFKS, or JCEHYBRIDRACFKS
      type: PKCS12
      pkcs12:
        # **COMMONLY_CUSTOMIZED**
        # Keystore directory
        directory: /zowe/keystore
        # # Lock the keystore directory to only accessible by Zowe runtime user and group.
        lock: true
        # **COMMONLY_CUSTOMIZED**
        # # Certificate alias name. Optional, default value is localhost.
        # # Note: please use all lower cases as alias.
        # name: localhost
        # **COMMONLY_CUSTOMIZED**
        # # Keystore password. Optional, default value is password.
        # password: password
        # **COMMONLY_CUSTOMIZED**
        # # Alias name of self-signed certificate authority. Optional, default value is local_ca.
        # # Note: please use all lower cases as alias.
        # caAlias: local_ca
        # **COMMONLY_CUSTOMIZED**
        # # Password of keystore stored self-signed certificate authority. Optional, default value is local_ca_password.
        # caPassword: local_ca_password
      # # Distinguished name for Zowe generated certificates. All optional.
      dname:
        caCommonName: ""
        commonName: ""
        orgUnit: ""
        org: ""
        locality: ""
        state: ""
        country: ""
      # # Validity days for Zowe generated certificates
      validity: 3650
      # # Domain names and IPs should be added into certificate SAN
      # # If this field is not defined,  zwe init  command will use
      # #  zowe.externalDomains .
      san:
      #   # sample domain name
        - xxxx.xxxx.xxxx.xxxx
      #   # sample IP address
        - 10.x.x.x.x
```

## Recommendation
### Run `zwe config validate` before 
I can recommend the shell command `zwe config validate -c ./TEST.YAML.txt.yaml`. This command will check the config and eventually prints the schema validation errors.

### Directories
It is recommended to set the `zowe.runtimeDirectory` as read only. If you follow this recommendation, you need to set these directories "outside" the `/zowe':
```
logDirectory: /zoweout/logs
workspaceDirectory: /zoweout/workspace
extensionDirectory: /zoweout/extensions
```

**Comment by mainframe-JMF** [comment]
Hello,

Thank you so much it helped me. Now I am getting error in using pkcs12

ZWEL0318E - Couldn't parse file '/u/xxxx/zowe.yaml': while parsing a block ma
pping at line 106, column 9, did not find expected key at line 108, column 11.  
Error: Could not load config for FILE(/u/xxxx/zowe.yaml):FILE(/zowe/files/def
aults.yaml), status=7   


zowe..yaml file
000102       type: PKCS12                                                      
000103       pkcs12:                                                           
000104         # **COMMONLY_CUSTOMIZED**                                       
000105         # Keystore directory                                            
000106         directory: /zowe/keystore                                       
000107         # # Lock the keystore directory to only accessible by Zowe runti
000108           lock: true                                                    
000109         # **COMMONLY_CUSTOMIZED**                                       
000110         # # Certificate alias name. Optional, default value is localhost
000111         # # Note: please use all lower cases as alias.                  
000112         # name: localhost                                               
000113         # **COMMONLY_CUSTOMIZED**                                       
000114         # # Keystore password. Optional, default value is password.     
000115         # password: password                                            
000116         # **COMMONLY_CUSTOMIZED**                                       
000117         # # Alias name of self-signed certificate authority. Optional, d

Prior running this , Should i be building the keystore ?

**Comment by Martin-Zeithaml** [comment]
Hi,
the error is probably caused by wrong indentation, YAML is sensitive about this:
I am guessing you have this in your config:
```yaml
        directory: /zowe/keystore
        # # Lock the keystore directory to only accessible by Zowe runtime user and group.
          lock: true
```
The correct version is the `lock` in the same column as `directory`:
```yaml
        directory: /zowe/keystore
        # # Lock the keystore directory to only accessible by Zowe runtime user and group.
        lock: true
```

Related to keystore, if the keystore does not exist, you will need one. Otherwise if it is already there, you can use existing one.
