### ISSUE TITLE
Issue with docs.zowe.org/stable/appendix/zowe-yaml-configuration/

### ISSUE THREAD

**Issue by dkelosky** [zowe/docs-site#3859]
## Description

These items from `zowe.yaml` are not documented and are allowed under `components.gateway`:

```yaml
    server:
      internal:
      # gateway supports internal connector
        enabled: false
        port: 7550
        ssl:
          enabled: false
```
