### ISSUE TITLE
Document `defaults.yaml` consequences

### ISSUE THREAD

**Issue by Martin-Zeithaml** [zowe/docs-site#4014]
When updating `zowe.yaml`, user might think, that commenting/deleting a component will disable such component. This is not true anymore if such component is set in defaults. The [default.yaml](https://github.com/zowe/zowe-install-packaging/blob/v3.x/staging/files/defaults.yaml) is "hidden" from the user point of view. Let's show this on the following example, where user will prepare config, which is different comparing to merged config:
## User's config
```yaml
components:
#  comp1:
 #   enabled: true
  comp2:
    enabled: true
```
## `Defaults.yaml`
```yaml
components:
  comp1:
    enabled: true
    port: 123
    timeTraveling: DeLorean
```

## Merged result
```yaml
components:
  comp1:
    enabled: true
    port: 123
    timeTraveling: DeLorean
  comp2:
    enabled: true
```
## Solution
```yaml
components:
# User must (in this case) keep comp1 and disabled it
  comp1:
    enabled: false
  comp2:
    enabled: true
```
**Bonus:** This is valid for `configmgr`. For example, if `zwe` command is used in `shell` version, there might not be merged config and then the behavior will be different comparing to `javascript` version of the same command.
