### ISSUE TITLE
Issue with docs.zowe.org/stable/user-guide/mvd-3270/

### ISSUE THREAD

**Issue by colinpaicemq** [zowe/docs-site#4375]
## Description

I see in /appServer-2025-05-06-07-42.log

"zowe": { 
  "workspaceDirectory": "/u/tmp/zowec/workspace", 
  "externalDomains": [ 
    "10.1.1.2" 
  ], 
  "environments": { 
    "ZWED_SSH_PORT": 22, 
    "ZWED_TN3270_PORT": 23, 
    "ZWED_TN3270_SECURITY": "telnet", 
    "ZWED_SSH_HOST": "10.1.1.2", 
    "ZWED_TN3270_HOST": "10.1.1.2", 
    "ZWED_TN3270_ROW": 24, 
    "ZWED_TN3270_COL": 80, 
    "ZWED_TN3270_MOD": "5" 
  }, 

But I cannot find these mentioned in the doc ( I searched for ZWED_TN3270_MOD) 
Are these user specifiable? If so please document them.

**Comment by balhar-jakub** [comment]
**Current Documentation State:**

The file `docs/user-guide/mvd-3270.md` **DOES document these environment variables** (lines 14-36):

You can customize the preferences in the yaml configuration via environment variables:
* `ZWED_TN3270_PORT`: port number
* `ZWED_TN3270_SECURITY`: `telnet` or `tls`
* `ZWED_TN3270_HOST`: host name 
* `ZWED_TN3270_ROW`: alternate rows
* `ZWED_TN3270_COL`: alternate columns  
* `ZWED_TN3270_MOD`: screen mode, following values are supported
  * `1`: 24x80
  * `2`: 32x80
  * `3`: 43x80
  * `4`: 27x132
  * `5`: Dynamic    
* `ZWED_TN3270_CODEPAGE`: CCSID, following values are supported
  * `037`, `1047`, `273`, `277`, `278`, `280`, `284`, `290`, `297`, `420`, `424`, `500`, `838`, `870`, `875`, `918`, `924`, `937`, ` 935`, `930`

Example of environment variables:
```yaml
zowe:
  environments:
    ZWED_TN3270_PORT: "23"
    ZWED_TN3270_SECURITY: "telnet"
    ZWED_TN3270_HOST: "lpar1.example.com"
    ZWED_TN3270_ROW: "24"
    ZWED_TN3270_COL: "80"
    ZWED_TN3270_MOD: "5"
    ZWED_TN3270_CODEPAGE: "1047"
```
